//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolGame.Game.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Sound : global::System.Configuration.ApplicationSettingsBase {
        
        private static Sound defaultInstance = ((Sound)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Sound())));
        
        public static Sound Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableBackgroundMusic {
            get {
                return ((bool)(this["EnableBackgroundMusic"]));
            }
            set {
                this["EnableBackgroundMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCorrectSound {
            get {
                return ((bool)(this["EnableCorrectSound"]));
            }
            set {
                this["EnableCorrectSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableWrongSound {
            get {
                return ((bool)(this["EnableWrongSound"]));
            }
            set {
                this["EnableWrongSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackgorundMusicFile {
            get {
                return ((string)(this["BackgorundMusicFile"]));
            }
            set {
                this["BackgorundMusicFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CorrectSoundFile {
            get {
                return ((string)(this["CorrectSoundFile"]));
            }
            set {
                this["CorrectSoundFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WrongSoundFile {
            get {
                return ((string)(this["WrongSoundFile"]));
            }
            set {
                this["WrongSoundFile"] = value;
            }
        }
    }
}
